### PR TITLE
Updated to OPP

### PR DESCRIPTION
**Pull request by clayfanatic**
I've updated to use the OPP system. Included a link to a Step-by-step ppt.

### CODE REVIEW

**Comment by moorepants** [comment]
@clayfanatic There are some build errors due to syntax issues:

```
$ pelican --verbose --fatal errors -s publishconf.py
WARNING: Document title missing in file /home/travis/build/moorepants/eme185/content/pages/instructor-guide.rst: Ensure exactly one top level section
WARNING: Document title missing in file /home/travis/build/moorepants/eme185/content/pages/microcontroller-tutorial-part-02.rst: Ensure exactly one top level section
ERROR: Could not process pages/purchasing.rst
  | SystemMessage: /home/travis/build/moorepants/eme185/content/pages/purchasing.rst:165: (WARNING/2) Enumerated list ends without a blank line; unexpected unindent.
CRITICAL: RuntimeError: Error encountered
```

**Comment by moorepants** [comment]
@clayfanatic I'd like to merge these today as it is the switch over day.

**Comment by clayfanatic** [comment]
Checks Pending

**Comment by clayfanatic** [comment]
Checks Pending

**Pull request merged**
